# Module - 1

# Pre-Processing

In [1]:
import pandas as p
import numpy as n

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
data=p.read_csv('child.csv')

In [4]:
data.head()

baseline_value  accelerations  fetal_movement  uterine_contractions  \
0             120          0.000             0.0                 0.000   
1             132          0.006             0.0                 0.006   
2             133          0.003             0.0                 0.008   
3             134          0.003             0.0                 0.008   
4             132          0.007             0.0                 0.008   

   light_decelerations  severe_decelerations  prolongued_decelerations  \
0                0.000                   0.0                       0.0   
1                0.003                   0.0                       0.0   
2                0.003                   0.0                       0.0   
3                0.003                   0.0                       0.0   
4                0.000                   0.0                       0.0   

   abnormal_short_term_variability  mean_value_of_short_term_variability  \
0                               73                                   0.5   
1                               17                                   2.1   
2                               16                                   2.1   
3                               16                                   2.4   
4                               16                                   2.4   

   percentage_of_time_with_abnormal_long_term_variability  ...  histogram_min  \
0                                                 43       ...             62   
1                                                  0       ...             68   
2                                                  0       ...             68   
3                                                  0       ...             53   
4                                                  0       ...             53   

   histogram_max  histogram_number_of_peaks  histogram_number_of_zeroes  \
0            126                          2                           0   
1            198                          6                           1   
2            198                          5                           1   
3            170                         11                           0   
4            170                          9                           0   

   histogram_mode  histogram_mean  histogram_median  histogram_variance  \
0             120             137               121                  73   
1             141             136               140                  12   
2             141             135               138                  13   
3             137             134               137                  13   
4             137             136               138                  11   

   histogram_tendency  fetal_health  
0                   1             2  
1                   0             1  
2                   0             1  
3                   1             1  
4                   1             1  

[5 rows x 22 columns]

In [5]:
data.shape

(2126, 22)

In [6]:
data.isnull().sum()

baseline_value                                            0
accelerations                                             0
fetal_movement                                            0
uterine_contractions                                      0
light_decelerations                                       0
severe_decelerations                                      0
prolongued_decelerations                                  0
abnormal_short_term_variability                           0
mean_value_of_short_term_variability                      0
percentage_of_time_with_abnormal_long_term_variability    0
mean_value_of_long_term_variability                       0
histogram_width                                           0
histogram_min                                             0
histogram_max                                             0
histogram_number_of_peaks                                 0
histogram_number_of_zeroes                                0
histogram_mode                          

# Drop the Given Dataset

In [7]:
df=data.dropna()

In [8]:
df.shape

(2126, 22)

In [9]:
df.head()

baseline_value  accelerations  fetal_movement  uterine_contractions  \
0             120          0.000             0.0                 0.000   
1             132          0.006             0.0                 0.006   
2             133          0.003             0.0                 0.008   
3             134          0.003             0.0                 0.008   
4             132          0.007             0.0                 0.008   

   light_decelerations  severe_decelerations  prolongued_decelerations  \
0                0.000                   0.0                       0.0   
1                0.003                   0.0                       0.0   
2                0.003                   0.0                       0.0   
3                0.003                   0.0                       0.0   
4                0.000                   0.0                       0.0   

   abnormal_short_term_variability  mean_value_of_short_term_variability  \
0                               73                                   0.5   
1                               17                                   2.1   
2                               16                                   2.1   
3                               16                                   2.4   
4                               16                                   2.4   

   percentage_of_time_with_abnormal_long_term_variability  ...  histogram_min  \
0                                                 43       ...             62   
1                                                  0       ...             68   
2                                                  0       ...             68   
3                                                  0       ...             53   
4                                                  0       ...             53   

   histogram_max  histogram_number_of_peaks  histogram_number_of_zeroes  \
0            126                          2                           0   
1            198                          6                           1   
2            198                          5                           1   
3            170                         11                           0   
4            170                          9                           0   

   histogram_mode  histogram_mean  histogram_median  histogram_variance  \
0             120             137               121                  73   
1             141             136               140                  12   
2             141             135               138                  13   
3             137             134               137                  13   
4             137             136               138                  11   

   histogram_tendency  fetal_health  
0                   1             2  
1                   0             1  
2                   0             1  
3                   1             1  
4                   1             1  

[5 rows x 22 columns]

In [10]:
df.isnull().sum()

baseline_value                                            0
accelerations                                             0
fetal_movement                                            0
uterine_contractions                                      0
light_decelerations                                       0
severe_decelerations                                      0
prolongued_decelerations                                  0
abnormal_short_term_variability                           0
mean_value_of_short_term_variability                      0
percentage_of_time_with_abnormal_long_term_variability    0
mean_value_of_long_term_variability                       0
histogram_width                                           0
histogram_min                                             0
histogram_max                                             0
histogram_number_of_peaks                                 0
histogram_number_of_zeroes                                0
histogram_mode                          

In [11]:
df.describe()

baseline_value  accelerations  fetal_movement  uterine_contractions  \
count     2126.000000    2126.000000     2126.000000           2126.000000   
mean       133.303857       0.003178        0.009481              0.004366   
std          9.840844       0.003866        0.046666              0.002946   
min        106.000000       0.000000        0.000000              0.000000   
25%        126.000000       0.000000        0.000000              0.002000   
50%        133.000000       0.002000        0.000000              0.004000   
75%        140.000000       0.006000        0.003000              0.007000   
max        160.000000       0.019000        0.481000              0.015000   

       light_decelerations  severe_decelerations  prolongued_decelerations  \
count          2126.000000           2126.000000               2126.000000   
mean              0.001889              0.000003                  0.000159   
std               0.002960              0.000057                  0.000590   
min               0.000000              0.000000                  0.000000   
25%               0.000000              0.000000                  0.000000   
50%               0.000000              0.000000                  0.000000   
75%               0.003000              0.000000                  0.000000   
max               0.015000              0.001000                  0.005000   

       abnormal_short_term_variability  mean_value_of_short_term_variability  \
count                      2126.000000                           2126.000000   
mean                         46.990122                              1.332785   
std                          17.192814                              0.883241   
min                          12.000000                              0.200000   
25%                          32.000000                              0.700000   
50%                          49.000000                              1.200000   
75%                          61.000000                              1.700000   
max                          87.000000                              7.000000   

       percentage_of_time_with_abnormal_long_term_variability  ...  \
count                                         2126.00000       ...   
mean                                             9.84666       ...   
std                                             18.39688       ...   
min                                              0.00000       ...   
25%                                              0.00000       ...   
50%                                              0.00000       ...   
75%                                             11.00000       ...   
max                                             91.00000       ...   

       histogram_min  histogram_max  histogram_number_of_peaks  \
count    2126.000000    2126.000000                2126.000000   
mean       93.579492     164.025400                   4.068203   
std        29.560212      17.944183                   2.949386   
min        50.000000     122.000000                   0.000000   
25%        67.000000     152.000000                   2.000000   
50%        93.000000     162.000000                   3.000000   
75%       120.000000     174.000000                   6.000000   
max       159.000000     238.000000                  18.000000   

       histogram_number_of_zeroes  histogram_mode  histogram_mean  \
count                 2126.000000     2126.000000     2126.000000   
mean                     0.323612      137.452023      134.610536   
std                      0.706059       16.381289       15.593596   
min                      0.000000       60.000000       73.000000   
25%                      0.000000      129.000000      125.000000   
50%                      0.000000      139.000000      136.000000   
75%                      0.000000      148.000000      145.000000   
max                     10.000000      187.000000      182.000000   

       histogram_median  histogr

In [12]:
df.columns

Index(['baseline_value', 'accelerations', 'fetal_movement',
       'uterine_contractions', 'light_decelerations', 'severe_decelerations',
       'prolongued_decelerations', 'abnormal_short_term_variability',
       'mean_value_of_short_term_variability',
       'percentage_of_time_with_abnormal_long_term_variability',
       'mean_value_of_long_term_variability', 'histogram_width',
       'histogram_min', 'histogram_max', 'histogram_number_of_peaks',
       'histogram_number_of_zeroes', 'histogram_mode', 'histogram_mean',
       'histogram_median', 'histogram_variance', 'histogram_tendency',
       'fetal_health'],
      dtype='object')

In [13]:
df.baseline_value.unique()

array([120, 132, 133, 134, 122, 151, 150, 131, 130, 129, 128, 124, 115,
       114, 116, 158, 156, 148, 149, 146, 144, 142, 136, 141, 138, 140,
       154, 145, 139, 125, 123, 159, 143, 119, 121, 127, 126, 118, 135,
       137, 147, 157, 117, 152, 112, 106, 110, 160], dtype=int64)

In [14]:
df.accelerations.unique()

array([0.   , 0.006, 0.003, 0.007, 0.001, 0.005, 0.009, 0.002, 0.008,
       0.004, 0.01 , 0.015, 0.013, 0.014, 0.011, 0.017, 0.012, 0.016,
       0.019, 0.018])

In [15]:
df.fetal_movement.unique()

array([0.   , 0.072, 0.222, 0.408, 0.38 , 0.441, 0.383, 0.451, 0.469,
       0.34 , 0.425, 0.334, 0.135, 0.099, 0.108, 0.112, 0.089, 0.103,
       0.085, 0.109, 0.079, 0.065, 0.055, 0.058, 0.047, 0.038, 0.012,
       0.018, 0.02 , 0.005, 0.003, 0.006, 0.001, 0.004, 0.009, 0.01 ,
       0.002, 0.008, 0.007, 0.028, 0.026, 0.107, 0.013, 0.016, 0.029,
       0.05 , 0.053, 0.011, 0.015, 0.022, 0.021, 0.017, 0.019, 0.025,
       0.014, 0.024, 0.023, 0.035, 0.054, 0.03 , 0.048, 0.088, 0.043,
       0.052, 0.091, 0.033, 0.092, 0.084, 0.115, 0.041, 0.04 , 0.027,
       0.031, 0.063, 0.06 , 0.071, 0.306, 0.298, 0.139, 0.189, 0.157,
       0.235, 0.36 , 0.455, 0.443, 0.47 , 0.477, 0.446, 0.481, 0.369,
       0.335, 0.43 , 0.346, 0.323, 0.375, 0.353, 0.045, 0.032, 0.051,
       0.036, 0.037, 0.049])

In [16]:
df.uterine_contractions.unique()

array([0.   , 0.006, 0.008, 0.01 , 0.013, 0.002, 0.003, 0.001, 0.004,
       0.005, 0.007, 0.009, 0.012, 0.011, 0.015, 0.014])

In [17]:
df.light_decelerations.unique()

array([0.   , 0.003, 0.009, 0.008, 0.001, 0.002, 0.005, 0.004, 0.012,
       0.01 , 0.014, 0.006, 0.007, 0.015, 0.011, 0.013])

In [18]:
df.severe_decelerations.unique()

array([0.   , 0.001])

In [19]:
df.prolongued_decelerations.unique()

array([0.   , 0.002, 0.003, 0.001, 0.004, 0.005])

In [20]:
df.abnormal_short_term_variability.unique()

array([73, 17, 16, 26, 29, 83, 84, 86, 64, 28, 21, 19, 24, 18, 23, 30, 34,
       80, 87, 22, 27, 40, 20, 43, 61, 70, 57, 58, 39, 41, 33, 25, 44, 46,
       45, 52, 53, 56, 65, 36, 35, 38, 62, 51, 67, 68, 72, 63, 60, 47, 50,
       69, 54, 55, 66, 48, 31, 32, 37, 49, 59, 14, 12, 13, 74, 75, 77, 71,
       76, 79, 78, 81, 42, 82, 15], dtype=int64)

In [21]:
df.mean_value_of_short_term_variability.unique()

array([0.5, 2.1, 2.4, 5.9, 6.3, 0.3, 1.9, 2. , 1.4, 1.5, 2.3, 1.7, 2.5,
       0.4, 0.2, 4.4, 6. , 4.5, 6.9, 2.9, 3.4, 3.2, 3.7, 3.6, 2.2, 1.6,
       1.8, 4.7, 4.9, 5. , 7. , 1.3, 4.1, 5.4, 1.2, 0.8, 1.1, 0.9, 1. ,
       0.7, 2.8, 3.9, 5.2, 4.8, 4.3, 0.6, 5.3, 2.6, 3.3, 3.8, 2.7, 3.1,
       5.7, 4. , 3.5, 3. , 4.2])

In [22]:
df.percentage_of_time_with_abnormal_long_term_variability.unique()

array([43,  0,  6,  5,  9,  8, 79, 72, 14, 71,  1, 40, 69, 54, 53, 38, 29,
       18, 21, 37, 20,  2,  3, 27, 67, 68, 75, 74,  7, 30, 49, 39, 31, 32,
       19, 16, 11, 34, 58, 13, 10, 15, 12, 25, 26,  4, 46, 57, 33, 23, 22,
       51, 52, 59, 78, 84, 62, 24, 45, 35, 41, 61, 56, 44, 81, 42, 77, 88,
       91, 47, 55, 82, 86, 60, 28, 17, 70, 48, 50, 36, 85, 64, 66, 90, 73,
       65, 63], dtype=int64)

In [23]:
df.mean_value_of_long_term_variability.unique()

array([ 2.4, 10.4, 13.4, 23. , 19.9,  0. , 15.6, 13.6, 10.6, 27.6, 29.5,
       12.9,  5.4,  7.9,  8.7, 10.9, 13.9,  8.8,  7.8,  8.5,  6.7,  4. ,
        6.8,  2.9,  4.8,  3.4, 10.5,  5. , 12.5,  6.3, 15.1, 21.7, 12.4,
       24.2, 18.8, 16.2, 19.6, 12.2, 13.5, 13.3, 11.4, 15.2, 15.7, 22.1,
       21.1, 16.6, 14.9, 12.8, 22.2,  3.3,  6.2,  5.1, 13.2,  5.5,  6.4,
        5.2, 11.6, 11.2,  5.7, 11.9, 10.3, 13. , 11.5, 17.7, 22.3, 21.3,
       25.9, 18.4, 15.8,  1.2, 23.4,  7.1,  6.5,  4.9,  5.3,  4.5,  4.6,
        9.5, 14.6, 17.3, 11. , 17.2, 13.1, 12.1, 19.3,  4.4, 10.1, 19.4,
        5.8,  3.9,  2.1,  7.4,  3.1,  3.8,  4.7, 10.8,  8. ,  8.6,  4.3,
        7.2,  9.1,  8.1, 26.3, 12.7, 35.7, 16.9, 18. ,  9. ,  9.6,  8.3,
       11.3,  8.9,  3.7,  3.2,  8.4,  8.2, 41.8, 50.7, 25.8, 15.9,  5.6,
       10.7, 14. , 10. , 14.1, 14.3, 15.3, 23.3, 12.3,  9.8,  7.7,  7. ,
       14.8,  7.6,  7.5,  2.5,  6.1, 17.9, 12.6, 15.4, 13.8,  3.5, 18.7,
       11.7,  0.9,  1.3, 15.5, 14.2,  9.3,  9.2,  9

In [24]:
df.histogram_width.unique()

array([ 64, 130, 117, 150,  68,  66,  87, 107, 125,  99, 112, 128, 141,
       145,  16,  12,  24,  10, 143, 149, 144, 126, 134, 138, 129,  98,
        93, 142, 148, 120,  55,  31,  18,  20, 100,  44,  28,  26, 111,
       103,  60,  37,  30, 104, 108,  92, 119, 140, 109, 136, 113,  15,
        17,  25,  21,  35,  83,  96,  84,  29,  82, 105,  62, 122, 118,
        54, 146,  53,  56,  94,  85,  77,  91,  11,  23,  40,  42,  22,
       147,  90, 121, 106,  52,  48,  46,  39,  33,  34,  81,  65,  57,
       124,  72,  89, 139, 127,  19,  27,  69,  63,  75,  38,  80,  36,
        71,  74,  14,   8, 110,  76,  79,  58, 114,   7,  78,   9,   5,
        97, 132,  13,  95,  41,  47, 123,  51, 135, 102, 116,  86, 115,
       133,  88,  45,  43, 137,  67,  59,  32, 131, 101,  70,  49,  73,
         3,   6,  61,  50, 162, 176, 161, 153, 163, 158, 180], dtype=int64)

In [25]:
df.histogram_min.unique()

array([ 62,  68,  53,  50,  56,  88,  71,  67,  59,  65,  54,  57, 114,
       118, 122,  55,  51,  52,  77, 142, 130, 136,  58, 148, 143,  78,
       134,  74,  81, 119, 132, 138,  60,  63,  73, 135, 139, 128, 121,
       101,  72,  97, 117,  80, 111,  95,  92,  75,  61, 153, 156, 159,
       133, 149, 147, 146, 155,  93, 115, 113, 116,  83,  86,  91,  69,
       129, 140, 145, 103, 109, 112,  90,  82, 125,  64, 120,  89, 141,
       107, 106, 110,  66, 131, 144, 126, 137, 108,  99, 151, 154, 123,
        70, 102,  98, 124,  79,  84, 127,  76, 158, 100, 105,  96,  94,
       152, 150,  87,  85, 104], dtype=int64)

In [26]:
df.histogram_max.unique()

array([126, 198, 170, 200, 130, 186, 154, 158, 174, 178, 177, 182, 199,
       146, 128, 191, 193, 194, 181, 195, 188, 153, 148, 197, 161, 184,
       166, 163, 171, 156, 185, 180, 179, 169, 168, 172, 176, 196, 187,
       167, 152, 165, 150, 142, 189, 144, 138, 173, 183, 141, 147, 149,
       143, 192, 135, 151, 133, 131, 136, 145, 175, 140, 137, 139, 129,
       160, 159, 155, 164, 190, 157, 162, 134, 132, 127, 213, 210, 125,
       123, 122, 238, 205, 204, 211, 228, 230], dtype=int64)

In [27]:
df.histogram_number_of_peaks.unique()

array([ 2,  6,  5, 11,  9,  0,  1,  7,  3, 13, 10,  8,  4, 12, 14, 15, 16,
       18], dtype=int64)

In [28]:
df.histogram_number_of_zeroes.unique()

array([ 0,  1,  3,  2,  4, 10,  5,  8,  7], dtype=int64)

In [29]:
df.histogram_mode.unique()

array([120, 141, 137,  76,  71, 122, 150, 135, 143, 134, 133, 129,  75,
       126, 128, 124, 123, 121, 125, 119, 117, 127, 116, 170, 151, 154,
       149, 147, 140, 142, 153, 162, 156, 144, 146, 152, 148, 145, 167,
       165, 161, 131, 132, 136, 139, 114, 163, 159, 138, 158, 157, 186,
       187, 180, 176, 115, 160,  90, 108,  97, 130, 155, 107, 112, 109,
       110, 169,  99,  86, 106, 113, 111,  98,  95,  91,  88, 164,  89,
       179, 105,  67,  60, 100,  93,  77, 103, 104,  69], dtype=int64)

In [30]:
df.histogram_mean.unique()

array([137, 136, 135, 134, 107, 122, 148, 125, 127, 128, 124, 129, 104,
        99, 126, 123, 119, 113, 120, 112, 116, 115, 117, 118, 168, 171,
       142, 131, 152, 155, 153, 154, 145, 140, 143, 156, 158, 157, 147,
       150, 164, 163, 151, 149, 130, 132, 114, 105, 162, 165, 169, 172,
       167, 161, 146, 121, 133, 160, 141, 144, 139, 138, 159, 166, 178,
       180, 182, 175, 173,  98,  90,  87, 106, 110, 109, 108, 111,  91,
       103, 101,  83,  84,  78,  85,  82, 100, 170, 102,  97,  92,  93,
        95,  81,  79,  76,  89,  88,  75,  94,  96,  86,  80,  73],
      dtype=int64)

In [31]:
df.histogram_median.unique()

array([121, 140, 138, 137, 107, 106, 123, 151, 141, 135, 133, 132, 129,
       120, 102, 125, 127, 117, 126, 115, 130, 118, 119, 124, 170, 172,
       152, 136, 154, 150, 156, 155, 147, 144, 159, 160, 153, 149, 158,
       166, 165, 148, 145, 157, 128, 134, 113, 164, 174, 168, 162, 163,
       139, 122, 161, 131, 143, 146, 142, 169, 180, 183, 186, 178, 171,
       176, 177, 116,  91, 167,  78,  77, 112, 114, 111, 110,  86,  79,
       108, 105, 109,  95,  94,  97, 101,  98,  93,  99, 100,  92,  87,
        90,  82, 103, 104], dtype=int64)

In [32]:
df.histogram_variance.unique()

array([ 73,  12,  13,  11, 170, 215,   3,   1,   9,  10,   7,  76,  43,
        70,  45,  36,  27, 138,  34, 148,   0,  89,  56,  66,  35,  25,
        24,  21,  19,  14,  23,  28,  75,  72, 108,   8,   4,   2,   5,
        18,  15,   6,  16,  55,  20,  86,  60, 117,  39,  30, 137,  65,
        41, 136,  38, 157, 106, 177,  52,  29,  54,  44,  37,  42,  17,
        22,  26,  33,  53,  62,  74,  69,  79,  83, 100,  31,  49,  51,
        95,  61,  47,  68,  40, 104,  48, 103, 129,  57,  85,  46,  32,
        82,  91,  90,  92,  64,  63,  59, 127, 114,  78,  84,  94,  97,
        80,  71, 101, 126, 134, 144,  50,  87, 115,  96, 116,  77, 119,
       110,  98, 113, 195, 182, 128,  88, 109, 121, 269, 250, 254, 243,
       241, 190, 147], dtype=int64)

In [33]:
df.histogram_tendency.unique()

array([ 1,  0, -1], dtype=int64)

In [34]:
df.fetal_health.unique()

array([2, 1, 3], dtype=int64)

In [35]:
df['label'] = df.fetal_health.map({1:0,2:1,3:1})

In [36]:
df.head()

baseline_value  accelerations  fetal_movement  uterine_contractions  \
0             120          0.000             0.0                 0.000   
1             132          0.006             0.0                 0.006   
2             133          0.003             0.0                 0.008   
3             134          0.003             0.0                 0.008   
4             132          0.007             0.0                 0.008   

   light_decelerations  severe_decelerations  prolongued_decelerations  \
0                0.000                   0.0                       0.0   
1                0.003                   0.0                       0.0   
2                0.003                   0.0                       0.0   
3                0.003                   0.0                       0.0   
4                0.000                   0.0                       0.0   

   abnormal_short_term_variability  mean_value_of_short_term_variability  \
0                               73                                   0.5   
1                               17                                   2.1   
2                               16                                   2.1   
3                               16                                   2.4   
4                               16                                   2.4   

   percentage_of_time_with_abnormal_long_term_variability  ...  histogram_max  \
0                                                 43       ...            126   
1                                                  0       ...            198   
2                                                  0       ...            198   
3                                                  0       ...            170   
4                                                  0       ...            170   

   histogram_number_of_peaks  histogram_number_of_zeroes  histogram_mode  \
0                          2                           0             120   
1                          6                           1             141   
2                          5                           1             141   
3                         11                           0             137   
4                          9                           0             137   

   histogram_mean  histogram_median  histogram_variance  histogram_tendency  \
0             137               121                  73                   1   
1             136               140                  12                   0   
2             135               138                  13                   0   
3             134               137                  13                   1   
4             136               138                  11                   1   

   fetal_health  label  
0             2      1  
1             1      0  
2             1      0  
3             1      0  
4             1      0  

[5 rows x 23 columns]

In [37]:
del df['fetal_health']

In [38]:
df.head()

baseline_value  accelerations  fetal_movement  uterine_contractions  \
0             120          0.000             0.0                 0.000   
1             132          0.006             0.0                 0.006   
2             133          0.003             0.0                 0.008   
3             134          0.003             0.0                 0.008   
4             132          0.007             0.0                 0.008   

   light_decelerations  severe_decelerations  prolongued_decelerations  \
0                0.000                   0.0                       0.0   
1                0.003                   0.0                       0.0   
2                0.003                   0.0                       0.0   
3                0.003                   0.0                       0.0   
4                0.000                   0.0                       0.0   

   abnormal_short_term_variability  mean_value_of_short_term_variability  \
0                               73                                   0.5   
1                               17                                   2.1   
2                               16                                   2.1   
3                               16                                   2.4   
4                               16                                   2.4   

   percentage_of_time_with_abnormal_long_term_variability  ...  histogram_min  \
0                                                 43       ...             62   
1                                                  0       ...             68   
2                                                  0       ...             68   
3                                                  0       ...             53   
4                                                  0       ...             53   

   histogram_max  histogram_number_of_peaks  histogram_number_of_zeroes  \
0            126                          2                           0   
1            198                          6                           1   
2            198                          5                           1   
3            170                         11                           0   
4            170                          9                           0   

   histogram_mode  histogram_mean  histogram_median  histogram_variance  \
0             120             137               121                  73   
1             141             136               140                  12   
2             141             135               138                  13   
3             137             134               137                  13   
4             137             136               138                  11   

   histogram_tendency  label  
0                   1      1  
1                   0      0  
2                   0      0  
3                   1      0  
4                   1      0  

[5 rows x 22 columns]

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2126 entries, 0 to 2125
Data columns (total 22 columns):
 #   Column                                                  Non-Null Count  Dtype  
---  ------                                                  --------------  -----  
 0   baseline_value                                          2126 non-null   int64  
 1   accelerations                                           2126 non-null   float64
 2   fetal_movement                                          2126 non-null   float64
 3   uterine_contractions                                    2126 non-null   float64
 4   light_decelerations                                     2126 non-null   float64
 5   severe_decelerations                                    2126 non-null   float64
 6   prolongued_decelerations                                2126 non-null   float64
 7   abnormal_short_term_variability                         2126 non-null   int64  
 8   mean_value_of_short_term_variability  

In [40]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...  
2121    False
2122    False
2123    False
2124    False
2125    False
Length: 2126, dtype: bool

In [41]:
sum(df.duplicated())

13

In [42]:
df.corr()

baseline_value  \
baseline_value                                            1.000000   
accelerations                                            -0.080560   
fetal_movement                                           -0.033436   
uterine_contractions                                     -0.146373   
light_decelerations                                      -0.159032   
severe_decelerations                                     -0.053518   
prolongued_decelerations                                 -0.104597   
abnormal_short_term_variability                           0.305570   
mean_value_of_short_term_variability                     -0.279607   
percentage_of_time_with_abnormal_long_term_vari...        0.285630   
mean_value_of_long_term_variability                      -0.032091   
histogram_width                                          -0.147679   
histogram_min                                             0.361619   
histogram_max                                             0.275110   
histogram_number_of_peaks                                -0.113933   
histogram_number_of_zeroes                               -0.004745   
histogram_mode                                            0.708993   
histogram_mean                                            0.723121   
histogram_median                                          0.789246   
histogram_variance                                       -0.133938   
histogram_tendency                                        0.293503   
label                                                     0.251875   

                                                    accelerations  \
baseline_value                                          -0.080560   
accelerations                                            1.000000   
fetal_movement                                           0.048235   
uterine_contractions                                     0.089674   
light_decelerations                                     -0.108615   
severe_decelerations                                    -0.043018   
prolongued_decelerations                                -0.127749   
abnormal_short_term_variability                         -0.279577   
mean_value_of_short_term_variability                     0.207170   
percentage_of_time_with_abnormal_long_term_vari...      -0.373943   
mean_value_of_long_term_variability                     -0.142363   
histogram_width                                          0.298631   
histogram_min                                           -0.154286   
histogram_max                                            0.394147   
histogram_number_of_peaks                                0.190452   
histogram_number_of_zeroes                              -0.006147   
histogram_mode                                           0.243610   
histogram_mean                                           0.270334   
histogram_median                                         0.272849   
histogram_variance                                       0.125704   
histogram_tendency                                       0.028420   
label                                                   -0.394760   

                                                    fetal_movement  \
baseline_value                                           -0.033436   
accelerations                                             0.048235   
fetal_movement                                            1.000000   
uterine_contractions                                     -0.068779   
light_decelerations                                       0.049228   
severe_decelerations                                     -0.010976   
prolongued_decelerations                                  0.265922   
abnormal_short_term_variability                          -0.103715   
mean_value_of_short_term_variability                      0.121314   
percentage_of_time_with_abnormal_long_term_vari...       -0.074096   
mean_value_of_long_term_variability                       0.011047   
histogram_wid

In [43]:
df['label'].value_counts()

0    1655
1     471
Name: label, dtype: int64

In [44]:
print("Minimum value of percentage_of_time_with_abnormal_long_term_variability is:", df.percentage_of_time_with_abnormal_long_term_variability.min())
print("Maximum value of percentage_of_time_with_abnormal_long_term_variability is:", df.percentage_of_time_with_abnormal_long_term_variability.max())

Minimum value of percentage_of_time_with_abnormal_long_term_variability is: 0
Maximum value of percentage_of_time_with_abnormal_long_term_variability is: 91


In [45]:
print("Minimum value of accelerations is:", df.accelerations.min())
print("Maximum value of accelerations is:", df.accelerations.max())

Minimum value of accelerations is: 0.0
Maximum value of accelerations is: 0.019


In [46]:
print("Minimum value of light_decelerations is:", df.light_decelerations.min())
print("Maximum value of light_decelerations is:", df.light_decelerations.max())

Minimum value of light_decelerations is: 0.0
Maximum value of light_decelerations is: 0.015


In [47]:
print("Minimum value of histogram_mean is:", df.histogram_mean.min())
print("Maximum value of histogram_mean is:", df.histogram_mean.max())

Minimum value of histogram_mean is: 73
Maximum value of histogram_mean is: 182
